# Generated by Django 4.0.3 on 2022-08-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('saldo', models.FloatField(default=0.0)),
                ('limite_maximo', models.FloatField(default=0.0)),
                ('limite_disponivel', models.FloatField(default=0.0)),
            ],
        ),
    ]
